-- 创建引用点赞表
create table if not exists quote_likes (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id) on delete cascade not null,
  quote_id bigint references quotes(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, quote_id)
);

-- 创建引用收藏表
create table if not exists quote_favorites (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id) on delete cascade not null,
  quote_id bigint references quotes(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, quote_id)
);

-- 添加RLS策略
alter table quote_likes enable row level security;
alter table quote_favorites enable row level security;

-- 创建点赞表的RLS策略
create policy "用户可以查看所有点赞"
  on quote_likes for select
  to authenticated
  using (true);

create policy "用户只能添加自己的点赞"
  on quote_likes for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "用户只能删除自己的点赞"
  on quote_likes for delete
  to authenticated
  using (auth.uid() = user_id);

-- 创建收藏表的RLS策略
create policy "用户可以查看所有收藏"
  on quote_favorites for select
  to authenticated
  using (true);

create policy "用户只能添加自己的收藏"
  on quote_favorites for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "用户只能删除自己的收藏"
  on quote_favorites for delete
  to authenticated
  using (auth.uid() = user_id); 