-- 创建引用点赞表
create table if not exists quote_likes (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id) on delete cascade not null,
  quote_id bigint references quotes(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, quote_id)
);

-- 创建引用收藏表
create table if not exists quote_favorites (
  id bigint primary key generated by default as identity,
  user_id uuid references auth.users(id) on delete cascade not null,
  quote_id bigint references quotes(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, quote_id)
);

-- 添加RLS策略
alter table quote_likes enable row level security;
alter table quote_favorites enable row level security;

-- 创建点赞表的RLS策略
create policy "启用认证用户读取点赞"
  on quote_likes for select
  to authenticated
  using (true);

create policy "启用认证用户添加点赞"
  on quote_likes for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "启用认证用户删除点赞"
  on quote_likes for delete
  to authenticated
  using (auth.uid() = user_id);

-- 创建收藏表的RLS策略
create policy "启用认证用户读取收藏"
  on quote_favorites for select
  to authenticated
  using (true);

create policy "启用认证用户添加收藏"
  on quote_favorites for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "启用认证用户删除收藏"
  on quote_favorites for delete
  to authenticated
  using (auth.uid() = user_id);

-- 确保 quotes 表有正确的 RLS 策略
alter table quotes enable row level security;

create policy "启用公开读取语录"
  on quotes for select
  using (true);

create policy "启用认证用户添加语录"
  on quotes for insert
  to authenticated
  with check (true);

create policy "启用认证用户更新语录"
  on quotes for update
  to authenticated
  using (true); 